- hosts: localhost

  tasks:
    - import_tasks: ../tasks/oh-my-tmux-symlink.yml

    - import_tasks: ../tasks/install-aws-cli.yml
      tags: ['aws']

    - name: colorize
      shell: |
        # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/colorize
        # https://github.com/alecthomas/chroma
        go get -u github.com/alecthomas/chroma/cmd/chroma

    - name: kube-aliases
      get_url:
        url: https://raw.githubusercontent.com/ahmetb/kubectl-alias/master/.kubectl_aliases
        dest: $HOME/.kubectl_aliases

    - name: tmuxinator-completion
      get_url:
        url: https://raw.githubusercontent.com/tmuxinator/tmuxinator/master/completion/tmuxinator.zsh
        dest: /usr/local/share/zsh/site-functions/_tmuxinator

    - name: Space Vim
      shell: |
        curl -sLf https://spacevim.org/install.sh | bash

    - name: Homebrew Cask CLI
      community.general.homebrew_cask:
        name: "{{ item }}"
      with_items:
        - font-hack-nerd-font # https://github.com/ryanoasis/nerd-font
        - vagrant
        - fly
        - git-credential-manager-core
        - fuse
        - font-fira-code
        - font-cascadia-code-pl

    # Version Manager
    - name: pyenv
      community.general.homebrew:
        name: pyenv
    - name: SDK Man
      shell: |
        curl -s "https://get.sdkman.io" | bash
    - name: rbenv
      community.general.homebrew:
        name: rbenv

    # SDK Man
    - name: SDK Man Packages
      become: yes
      user:
        name: $(whoami)
        shell: |
          $(which zsh)
          sdk install {{ item }}
      with_items:
        - gradle
        - gradleprofiler
        - micronaut
