- hosts: localhost

  tasks:
    - name: fzf
      shell: |
        $(brew --prefix)/opt/fzf/install
      tags: ['fzf']

    - name: zinit
      shell: |
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/zdharma/zinit/master/doc/install.sh)"

    - name: zprezto
      shell: |
        # https://github.com/belak/prezto-contrib#usage
        cd ${ZPREZTODIR}
        git clone --recurse-submodules https://github.com/belak/prezto-contrib contrib

    # - name: YouCompleteMe
    #   shell: |
    #     # YouCompleteMe
    #     # Issue: YouCompleteMe unavailable: requires Vim compiled with Python
    #     # Fixing YouCompleteMe with python3: https://github.com/neovim/pynvim
    #     pip install pynvim
    #     cd ~/.config/nvim/bundle/YouCompleteMe
    #     python install.py --all